import React, { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  WalletCards,
  Download,
  Eye,
  Filter,
  ArrowLeft,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';
import { mockMySalarySummary, mockMyPayslips } from '../../data/mockMyPayroll';
import { MyPayslip } from '../../types/employeePayroll';
import { StatusBadge } from '../../components/ui/StatusBadge';
import { MyPayslipDetailModal } from '../../components/employee/payroll/MyPayslipDetailModal';
import { Toast, ToastMessage } from '../../components/ui/Toast';

export const PayrollPage: React.FC = () => {
  const navigate = useNavigate();
  const [selectedYear, setSelectedYear] = useState<number>(2026);
  const [viewingPayslip, setViewingPayslip] = useState<MyPayslip | null>(null);
  const [toast, setToast] = useState<ToastMessage | null>(null);

  const showToast = (type: 'success' | 'error' | 'info', title: string, message?: string) => {
    setToast({ id: `toast-${Date.now()}`, type, title, message: message || '' });
  };

  const formatCurrency = (val: number) => `₹${val.toLocaleString('en-IN')}`;

  // Filter payslips by year
  const filteredPayslips = useMemo(() => {
    return mockMyPayslips.filter((p) => p.year === selectedYear);
  }, [selectedYear]);

  const handleDownloadPDF = (payslip: MyPayslip) => {
    showToast('info', 'Downloading Payslip', `Generating formatted PDF statement for ${payslip.month}.`);
    
    const payslipText = `
====================================================================
                        DAYFLOW HRMS PAYSLIP
====================================================================
Pay Period: ${payslip.month}
Employee Name: Sanjay Jayarajan
Department: Engineering
Designation: Senior Tech Lead
Status: ${payslip.status.toUpperCase()}
Disbursed Date: ${payslip.date}
--------------------------------------------------------------------
EARNINGS
--------------------------------------------------------------------
Basic Pay:                  ${formatCurrency(payslip.basicPay)}
House Rent Allowance (HRA): ${formatCurrency(payslip.hra)}
${payslip.allowances.map((a) => `${a.label.padEnd(27, ' ')}: ${formatCurrency(a.amount)}`).join('\n')}
--------------------------------------------------------------------
GROSS SALARY:               ${formatCurrency(payslip.grossSalary)}
====================================================================
DEDUCTIONS
--------------------------------------------------------------------
${payslip.deductions.map((d) => `${d.label.padEnd(27, ' ')}: ${formatCurrency(d.amount)}`).join('\n')}
--------------------------------------------------------------------
TOTAL DEDUCTIONS:           ${formatCurrency(payslip.totalDeductions)}
====================================================================
NET SALARY DISBURSED:       ${formatCurrency(payslip.netSalary)}
====================================================================
Confidential Document - Generated by Dayflow HRMS
    `.trim();

    setTimeout(() => {
      const element = document.createElement('a');
      const file = new Blob([payslipText], { type: 'text/plain;charset=utf-8' });
      element.href = URL.createObjectURL(file);
      element.download = `Payslip_Sanjay_Jayarajan_${payslip.month.replace(/\s+/g, '_')}.txt`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      showToast('success', 'Download Complete', `Payslip for ${payslip.month} downloaded successfully.`);
    }, 600);
  };

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/employee/dashboard')}
            className="p-2 text-slate-500 hover:text-slate-900 hover:bg-slate-100 rounded-xl transition-colors"
            aria-label="Back to dashboard"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight flex items-center gap-2">
              My Payroll & Payslips <Sparkles className="w-5 h-5 text-teal-500 fill-teal-500/20" />
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
              Access your confidential monthly compensation statements and tax vouchers.
            </p>
          </div>
        </div>
      </div>

      {/* Current Salary Summary Card (View-Only) */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-teal-950 text-white rounded-2xl p-6 shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 translate-x-4 -translate-y-4 w-48 h-48 bg-teal-500/10 rounded-full blur-2xl pointer-events-none" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2.5 py-0.5 rounded-md bg-teal-500/20 border border-teal-400/30 text-teal-300 text-xs font-bold uppercase tracking-wider">
                Current Pay Cycle ({mockMySalarySummary.payPeriod})
              </span>
              <span className="text-xs text-slate-400 flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5 text-teal-400" /> Confidential
              </span>
            </div>
            <p className="text-xs text-slate-300 font-medium">Net Disbursed Salary</p>
            <p className="text-3xl sm:text-4xl font-extrabold text-emerald-400 mt-1">
              {formatCurrency(mockMySalarySummary.netSalary)}
            </p>
            <p className="text-xs text-slate-400 mt-2">
              Disbursed via <span className="text-slate-200 font-semibold">{mockMySalarySummary.paymentMethod}</span> ({mockMySalarySummary.bankAccount})
            </p>
          </div>

          {/* Breakdown summary columns */}
          <div className="bg-white/10 backdrop-blur-md p-4 rounded-xl border border-white/10 grid grid-cols-2 gap-4 text-xs shrink-0">
            <div>
              <span className="text-slate-400 block font-medium">Gross Compensation</span>
              <span className="text-base font-extrabold text-slate-100 mt-0.5 block">
                {formatCurrency(mockMySalarySummary.grossSalary)}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block font-medium">Total Deductions</span>
              <span className="text-base font-extrabold text-red-300 mt-0.5 block">
                -{formatCurrency(mockMySalarySummary.totalDeductions)}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Payslip History Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-slate-900">Payslip Archive & History</h3>
          <div className="flex items-center gap-1.5 bg-slate-50 px-3 py-1.5 rounded-xl border border-slate-200 text-xs">
            <Filter className="w-3.5 h-3.5 text-slate-400" />
            <span className="text-slate-500 font-medium">Year:</span>
            <select
              value={selectedYear}
              onChange={(e) => setSelectedYear(Number(e.target.value))}
              className="bg-transparent text-slate-800 font-bold focus:outline-none text-xs cursor-pointer"
            >
              <option value={2026}>2026</option>
              <option value={2025}>2025</option>
            </select>
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-slate-100/90 shadow-xs overflow-hidden">
          {filteredPayslips.length > 0 ? (
            <div className="divide-y divide-slate-100">
              {filteredPayslips.map((slip) => (
                <div
                  key={slip.id}
                  className="p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-slate-50/60 transition-colors text-xs"
                >
                  <div className="flex items-center gap-3.5">
                    <div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 font-bold flex items-center justify-center shrink-0 border border-teal-100">
                      <WalletCards className="w-5 h-5" />
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-900 text-sm">{slip.month}</h4>
                      <p className="text-slate-500 mt-0.5">
                        Gross: {formatCurrency(slip.grossSalary)} • Net Payout:{' '}
                        <span className="font-bold text-slate-800">{formatCurrency(slip.netSalary)}</span>
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center justify-between sm:justify-end gap-3 pt-2 sm:pt-0 border-t sm:border-t-0 border-slate-100">
                    <StatusBadge status="paid" size="sm" />
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => setViewingPayslip(slip)}
                        className="flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-teal-50 hover:text-teal-700 rounded-xl transition-all"
                      >
                        <Eye className="w-3.5 h-3.5" /> View
                      </button>
                      <button
                        onClick={() => handleDownloadPDF(slip)}
                        className="flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-white bg-teal-600 hover:bg-teal-700 rounded-xl transition-all shadow-2xs"
                      >
                        <Download className="w-3.5 h-3.5" /> PDF
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="py-16 text-center text-slate-400 space-y-2">
              <WalletCards className="w-8 h-8 mx-auto text-slate-300" />
              <p className="text-sm font-semibold text-slate-700">No payslips found for {selectedYear}</p>
              <p className="text-xs text-slate-400">Your payslips will appear here once processed by HR.</p>
            </div>
          )}
        </div>
      </div>

      {/* Payslip View Modal */}
      <MyPayslipDetailModal
        isOpen={Boolean(viewingPayslip)}
        payslip={viewingPayslip}
        onClose={() => setViewingPayslip(null)}
      />

      {/* Toast Feedback */}
      <Toast toast={toast} onDismiss={() => setToast(null)} />
    </div>
  );
};
